export const TYPES = {
    AUTH_SIGNIN:"AUTH_LOGIN",
    AUTH_SIGNOUT:"AUTH_LOGOUT",
    AUTH_SIGNUP:"AUTH_REGISTER",
    ALERT_NOTIFIER_ON:"ALERT_NOTIFIER_ON",
    ALERT_NOTIFIER_OFF:"ALERT_NOTIFIER_OF",
    GET_ALL_PRODUCTS:"GET_ALL_PRODUCTS",
}