export const TYPES = {
    AUTH_SIGNIN:"AUTH_LOGIN",
    AUTH_SIGNOUT:"AUTH_LOGOUT",
    AUTH_SIGNUP:"AUTH_REGISTER",
    ALERT_NOTIFIER_ON:"ALERT_NOTIFIER_ON",
    ALERT_NOTIFIER_OFF:"ALERT_NOTIFIER_OF",
    GET_ALL_PRODUCTS:"GET_ALL_PRODUCTS",
    GET_UNIT:"GET_UNIT",
    GET_PRODUCTS_BY_CATE:"GET_PRODUCTS_BY_CATE",
    POST_ADD_PRODUCT:"POST_ADD_PRODUCT",
    POST_ADD_CATE_PRODUCT:"POST_ADD_CATE_PRODUCT",
    POST_ADD_BUNKER_PRODUCT:"POST_ADD_BUNKER_PRODUCT",
    POST_ADD_PRODUCER_PRODUCT:"POST_ADD_PRODUCER_PRODUCT",
    POST_ADD_UNIT_PRODUCT:"POST_ADD_UNIT_PRODUCT",
    POST_ADD_SUPLIER:"POST_ADD_SUPLIER",
    DELETE_PRODUCTS:"DELETE_PRODUCTS",
    SET_DATA_BILLS_IMPORT:"SET_DATA_BILLS_IMPORT",

}